name: isar_benchmark

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  isar: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.2

  objectbox: ^2.1.0
  objectbox_flutter_libs: any

  realm: ^1.3.0

  path_provider: ^2.0.15
  english_words: ^4.0.0
  fl_chart: ^0.63.0
  share_plus: ^7.0.2
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_lints: ^2.0.2
  build_runner: any
  objectbox_generator: any

flutter:
  uses-material-design: true
