name: isar_benchmark

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14

  objectbox: ^4.1.0
  objectbox_flutter_libs: any

  realm: ^20.0.1

  path_provider: ^2.1.5
  english_words: ^4.0.0
  fl_chart: ^0.70.2
  share_plus: ^10.1.4
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: any
  objectbox_generator: any

flutter:
  uses-material-design: true
